// Auth
export {
  refreshToken,
  requestPasswordReset,
  confirmPasswordReset,
  getProfile,
  updateName,
  updatePassword,
  toggle2FA,
  verify2FA,
  resend2FA,
  get2FAStatus,
  uploadProfilePicture,
  deleteProfilePicture,
  verifyToken,
  acceptInvitation,
} from './auth';

// Finance
export {
  getEntities,
  getDashboardData,
  getBeneficiaries,
  getBeneficiariesForCA,
  getBeneficiary,
  addBeneficiary,
  updateBeneficiary,
  deleteBeneficiary,
  getBankAccountsForBeneficiary,
  getBankAccountsForBeneficiaryDropdown,
  addBankAccount,
  deactivateBankAccount,
  reactivateBankAccount,
  deleteBankAccount,
  getOrganisationBankAccounts,
  getOrganisationBankAccountsDropdown,
  getOrganisationBankAccountsForCA,
  addOrganisationBankAccount,
  updateOrganisationBankAccount,
  deleteOrganisationBankAccount,
  getInvoicesList,
  getInvoices,
  addInvoice,
  updateInvoice,
  deleteInvoice,
  getInvoiceAttachment,
  getInvoicePdf,
  getVouchersList,
  getVouchers,
  addVoucher,
  updateVoucher,
  deleteVoucher,
  getCAVoucher,
  updateCAVoucher,
  deleteCAVoucher,
  getVoucherQuick,
  getVoucher,
  getVoucherAttachment,
  getVoucherPdf,
  getCATeamVouchers,
  getCATeamInvoices,
  getCATeamVouchersBulk,
  getCATeamInvoicesBulk,
  getCATeamInvoiceAttachment,
  exportVouchersToTallyXML,
  exportVouchers,
  exportInvoices,
  getActivityLog,
  createActivityLog,
  getClientDocumentActivityLogs,
  getAccountantDashboardStats,
  getFinancePendingCaApprovalIndicator,
  getFinancePendingMasterAdminApprovalIndicator,
  getEntityIndicators,
  getInvoiceAnalytics,
  getVoucherAnalytics,
  getNoticeAttachment,
  getCACompanyProfile,
  createCACompanyProfile,
  updateCACompanyProfile,
} from './finance';

// Documents
export {
  getDocuments,
  createFolder,
  uploadFile,
  deleteDocument,
  shareDocument,
  viewFile,
  getSharedDocuments,
  getSharedFolderContents,
  createPublicShareTokenDocument,
  createPublicShareTokenFolder,
  revokePublicShareTokenDocument,
  revokePublicShareTokenFolder,
  getPublicFolder,
  getPublicSubfolder,
  viewPublicDocument,
  shareFolder,
  createCAFolder,
  uploadCAFile,
  renameFolder,
} from './documents';

// Services
export {
  createService,
  listServices,
  getServiceDetails,
  deleteService,
  updateServiceSettings,
  getChecklist,
  addChecklistItem,
  deleteChecklistItem,
  updateChecklistItem,
  getSubtasks,
  addSubtask,
  deleteSubtask,
  getSupportingFiles,
  addSupportingFile,
  deleteSupportingFile,
  getClientCountForService,
  listAssignedClientIdsForService,
  getServiceDeletionStatus,
} from './services';

// Organisation
export {
  listOrganisations,
  createOrganisation,
  updateOrganisation,
  deleteOrganisation,
  listAllEntities,
  listEntities,
  createEntity,
  updateEntity,
  deleteEntity,
  listOrgUsers,
  resendToken,
  inviteOrganizationUser,
  deleteOrgUser,
  inviteEntityUser,
  listEntityUsers,
  deleteEntityUser,
  deleteInvitedOrgUser,
  listAllEntityUsers,
  listAllClientUsers,
  addEntityUsers,
  inviteCaTeamMember,
  deleteCaTeamMember,
  listAllAccessibleEntityUsers,
} from './organisation';

// Clients
export {
  listClients,
  listClientsByOrganization,
  createClient,
  updateClient,
  uploadClientPhoto,
  deleteClientPhoto,
  deleteClient,
  listClientPortals,
  createClientPortal,
  updateClientPortal,
  revealClientPortalSecret,
  deleteClientPortal,
  listClientServices,
  addServicesToClient,
  removeServicesFromClient,
  getClientDashboard,
  getClientTeamMembers,
  getAllClientTeamMembers,
  assignTeamMembers,
  removeTeamMember,
  getClientBillingInvoices,
  getInvoicePaymentDetails,
  uploadClientInvoicePaymentProof,
  getPaymentProofUrl,
  markInvoicePaid,
  updateClientBillingInvoiceStatus,
  getMyCompany,
  updateMyCompany,
  getInvoicePDFBlob,
  downloadInvoicePDF,
  updateClientBillingInvoice,
  lockClient,
  unlockClient,
} from './clients';

// Client Billing
// Also export updateClientBillingInvoice directly to ensure it's available
export { updateClientBillingInvoice, getInvoicePDFBlob } from './clients';

export {
  getClientBillingSetup,
  createOrUpdateClientBilling,
  updateClientBilling,
  bulkUpdateServiceBillings,
  generateInvoicesNow,
} from './clientBilling';

// Payments
export {
  getInvoicesWithPaymentStatus,
  getPaymentQRCode,
  uploadPaymentProof,
  getPaymentQRSettings,
  createPaymentQRSettings,
  updatePaymentQRSettings,
} from './payments';

// Settings
export {
  getGeneralSettings,
  updateGeneralSettings,
  getTags,
  createTag,
  updateTag,
  deleteTag,
  getPortals,
  createPortal,
  deletePortal,
  getBusinessTypes,
  createBusinessType,
  updateBusinessType,
  deleteBusinessType,
  getFinanceHeaders,
  createFinanceHeader,
  updateFinanceHeader,
  deleteFinanceHeader,
} from './settings';

// Team
export {
  inviteTeamMember,
  listTeamMembers,
  listCATeamForClient,
  updateTeamMember,
  deleteTeamMember,
  resendInvite,
  listDepartments,
} from './team';

// Tasks
export {
  listTasks,
  createTask,
  getTaskDetails,
  getTaskHistory,
  updateTask,
  deleteTask,
  startTaskTimer,
  stopTaskTimer,
  addManuallyLoggedTime,
  listTodos,
  createTodo,
  updateTodo,
  deleteTodo,
  addTaskSubtask,
  updateTaskSubtask,
  deleteTaskSubtask,
  listTaskStages,
  createTaskStage,
  updateTaskStage,
  deleteTaskStage,
  listTaskComments,
  createTaskComment,
  updateTaskComment,
  deleteTaskComment,
  getUnreadNotificationCount,
  getTaskDashboardAnalytics,
  addTaskCollaborator,
  removeTaskCollaborator,
  getTaskCollaborators,
  getCommentReadReceipts,
  requestTaskClosure,
  getClosureRequest,
  reviewClosureRequest,
} from './tasks';

// Recurring Tasks
export {
  listRecurringTasks,
  getRecurringTask,
  createRecurringTask,
  updateRecurringTask,
  deleteRecurringTask,
  triggerRecurringTaskScheduler,
} from './recurringTasks';

// Notices
export {
  getNotices,
  getNotice,
  createNotice,
  uploadNotice,
  requestNoticeClosure,
  approveNoticeClosure,
  rejectNoticeClosure,
  getNoticeComments,
  addNoticeComment,
  addNoticeCollaborator,
  removeNoticeCollaborator,
  deleteNotice,
  getUnreadNoticeCount,
  markNoticeCommentAsRead,
  getNoticeCommentReadReceipts,
  getNoticeDashboardAnalytics,
} from './notices';

// Folder Templates
export {
  listTemplates,
  createTemplate,
  updateTemplate,
  deleteTemplate,
  applyTemplate,
} from './folderTemplates';
